site_name: Kithon

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - python
    palette:
      - media: '(prefers-color-scheme: light)'
        scheme: default
        primary: teal
        accent: amber

repo_name: alploskov/kithon
repo_url: https://github.com/alploskov/kithon
nav:
  - Kithon: index.md
  - Tools: tools.md
  - Kithon-lang: kithon-lang.md
  - API: api.md
  - Tutorial: tutorial.md

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
  - js/termynal.js
  - js/custom.js
