[tool.poetry]
name = "transPYler"
version = "0.0.1"
description = ""
authors = ["Aleksey Ploskov"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Jinja2 = "^3.0.2"
PyYaml = "^5.4.0"

[tool.poetry.scripts]
tpy = "transpyler.cli:tpy"
tpy-gen = "transpyler.cli:tpy_gen"
tpy-new = "transpyler.cli:tpy_new"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"