[tool.poetry]
name = "transPYler"
version = "1.1.0"
description = ""
authors = ["Aleksey Plskov"]
license = "MIT"
include = ["a.txt"]

[tool.poetry.dependencies]
python = "^3.9"
Jinja2 = "^3.0.2"
PyYAML = "^6.0"
typer = "^0.4.0"
coconut = "^1.5.0"

[tool.poetry.scripts]
tpy = "transpyler.cli:tpy"
tpy-gen = "transpyler.cli:tpy_gen"
tpy-new = "transpyler.cli:tpy_new"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
