[tool.poetry]
name = "transPYler"
version = "0.1.0"
description = ""
authors = ["Aleksey Plskov"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Jinja2 = "^3.0.2"
PyYAML = "^6.0"
typer = "^0.4.0"
coconut = "^1.5.0"

[tool.poetry.scripts]
tpy = "transpyler.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
